export const SEED_SOPS = [
  // Opening Procedures (6)
  { category: 'Opening Procedures', title: 'Daily Opening Checklist', content: `1. Arrive at least 30 minutes before trading (10:00 AM open)\n2. Unlock premises and disable alarm\n3. Switch on all equipment: fryers, grill, holding cabinets, POS terminal\n4. Check refrigeration temperatures — all fridges must be ≤5°C, freezers ≤-18°C. Log in SFBB diary\n5. Check ingredient stock levels against opening par levels\n6. Prepare chicken brine if required\n7. Turn on ventilation and extraction\n8. Clean and sanitise all food-contact surfaces\n9. Set up till: check float (£150 standard)\n10. Brief any staff opening with you\n11. Confirm delivery platform tablets are charged and online\n12. Open at 10:30 AM sharp` },
  { category: 'Opening Procedures', title: 'Fryer Pre-Heat Procedure', content: `1. Check oil level — top up if below minimum fill line\n2. Check oil colour and smell — discard if dark or rancid (replace policy: every 3 days peak, 5 days off-peak)\n3. Turn fryer power on — target oil temperature 175°C\n4. Allow minimum 15 minutes to reach operating temperature\n5. Do NOT add food until oil is fully at temperature\n6. Log fryer oil change date in equipment log\n7. Keep fire blanket and fire extinguisher accessible at all times` },
  { category: 'Opening Procedures', title: 'Temperature Log — Morning Check', content: `1. Check all refrigeration units using probe thermometer at opening\n2. Fridge 1 (raw chicken): must be ≤3°C\n3. Fridge 2 (prepared/cooked): must be ≤5°C\n4. Freezer 1 (frozen stock): must be ≤-18°C\n5. Record all readings in SFBB Temperature Log with your name and date\n6. If any unit is outside range, do not use and contact manager immediately\n7. Cross-reference against previous night's closing readings` },
  { category: 'Opening Procedures', title: 'POS and Till Opening', content: `1. Power on POS terminal and confirm network connection\n2. Log in with your staff credentials\n3. Count till float — standard opening float: £150\n4. Record float count on daily cash sheet\n5. Check receipt paper and replace if needed\n6. Confirm all menu items are correctly priced\n7. Check delivery platform tablets: Uber Eats, Just Eat, Deliveroo all online\n8. Test card machine with a £0.01 test transaction if any doubt\n9. Report any discrepancies to manager before opening` },
  { category: 'Opening Procedures', title: 'Prep Station Setup', content: `1. Sanitise all prep surfaces with approved food-safe sanitiser\n2. Set up portion scales and check calibration (zero before use)\n3. Prepare sauces: check batch dates, discard anything over 3 days\n4. Stock bread rolls, fries, coleslaw to service levels\n5. Set up packaging station: boxes, bags, napkins, condiment sachets\n6. Prepare allergen information — ensure allergen matrix is visible\n7. Check serving utensils are clean and allocated per station` },
  { category: 'Opening Procedures', title: 'Delivery Platform Morning Setup', content: `1. Power on all delivery tablets (Uber Eats, Just Eat, Deliveroo)\n2. Confirm all platforms show store as OPEN at correct opening time\n3. Check for any messages or special notes from overnight\n4. Verify menu prices match current menu — flag discrepancies to manager\n5. Confirm estimated delivery time is set appropriately\n6. Test accepting an order if available during test mode\n7. Keep tablets charged — connect to charging cable on busy periods` },

  // Closing Procedures (6)
  { category: 'Closing Procedures', title: 'Daily Closing Checklist', content: `1. Stop accepting orders 15 minutes before close\n2. Serve remaining customers and clear kitchen\n3. Turn off delivery platforms one by one: Uber Eats, Just Eat, Deliveroo\n4. Drain fryer oil into approved container — DO NOT pour down drain\n5. Clean and degrease all surfaces\n6. Empty and clean all bins — replace liners\n7. Check all refrigeration temperatures — log in SFBB diary\n8. Lock away cash — complete end-of-day till count\n9. Switch off all equipment except refrigeration\n10. Set alarm and lock premises\n11. Complete CoopOS Night Summary via manager login` },
  { category: 'Closing Procedures', title: 'End-of-Day Till Count', content: `1. Print Z-report from POS terminal\n2. Remove all cash from till except £150 float\n3. Count cash by denomination:\n   - £50 notes\n   - £20 notes\n   - £10 notes\n   - £5 notes\n   - £2 coins\n   - £1 coins\n   - Silver and bronze\n4. Record total on daily cash count sheet\n5. Compare against POS Z-report cash total\n6. Record any variance — variances over £5 must be investigated and reported\n7. Seal cash in cash bag and place in safe\n8. Log till count in CoopOS Finance module` },
  { category: 'Closing Procedures', title: 'Kitchen Deep Clean — Daily', content: `1. Allow all surfaces to cool before cleaning\n2. Remove all removable parts: grill plates, fryer baskets\n3. Soak removable parts in hot soapy water for 10 minutes\n4. Degrease main cooking surfaces with approved degreaser\n5. Clean inside of microwave, holding cabinets, and warming drawers\n6. Sweep and mop kitchen floor (anti-slip mop head)\n7. Wipe down all stainless steel surfaces — use stainless steel cleaner\n8. Clean extraction filters — remove and soak weekly\n9. Sanitise all food-contact surfaces with food-safe sanitiser\n10. Record completion in SFBB Cleaning Schedule` },
  { category: 'Closing Procedures', title: 'Fryer Shutdown and Cleaning', content: `1. Turn off fryer at close of service\n2. Allow oil to cool to below 40°C before any cleaning (FIRE RISK)\n3. Drain oil into approved oil container for disposal or filtration\n4. Remove fry baskets and soak in degreaser\n5. Clean inside of fryer tank with long-handled brush\n6. Wipe down exterior with degreaser\n7. Replace filtered or fresh oil before closing if trading next day\n8. Never leave fryer unattended while heating\n9. Record oil disposal in waste log` },
  { category: 'Closing Procedures', title: 'Stock Count — Closing', content: `1. Count all remaining ingredients at close\n2. Record counts in CoopOS Stock module under daily stocktake\n3. Highlight any items below par level — flag for next day delivery\n4. Check all deliveries received that day are entered in system\n5. Ensure all waste logged during the day is recorded in CoopOS Wastage module\n6. Place orders for next-day delivery if required\n7. Store all perishables correctly — label with date opened/prepared` },
  { category: 'Closing Procedures', title: 'Closing Temperature Log', content: `1. At close of service, check all refrigeration temperatures\n2. Fridge 1 (raw chicken): must be ≤3°C\n3. Fridge 2 (prepared): must be ≤5°C\n4. Freezer: must be ≤-18°C\n5. Record all readings in SFBB Temperature Log\n6. If any readings are out of range, investigate and document action taken\n7. Ensure all hot-held food is discarded — never refrigerate hot-held food for reuse` },

  // Food Preparation (8)
  { category: 'Food Preparation', title: 'Chicken Breading Procedure', content: `1. Remove raw chicken from fridge — ensure it is ≤3°C before use\n2. Prepare brine: 2 litres water, 50g salt, 25g sugar — stir until dissolved\n3. Submerge chicken pieces fully in brine for minimum 2 hours (overnight preferred)\n4. Remove from brine, pat dry with food-safe paper\n5. Coat in seasoned flour: shake off excess\n6. Dip in buttermilk wash\n7. Re-coat in seasoned flour — press firmly\n8. Place coated pieces on tray — do NOT stack\n9. Cook within 30 minutes of breading or refrigerate at ≤5°C\n10. NEVER reuse brine — discard after each batch\n11. Wash hands thoroughly after handling raw chicken` },
  { category: 'Food Preparation', title: 'Frying Times and Temperatures', content: `Required oil temperature: 175°C\n\nCooking times:\n- Chicken breast (bone-in): 14–16 minutes\n- Chicken thigh (bone-in): 13–15 minutes\n- Chicken wings: 10–12 minutes\n- Chicken tenders/strips: 6–8 minutes\n- Chicken burger (fillet): 7–9 minutes\n- Fries (fresh): 4–5 minutes at 180°C\n- Fries (frozen): 3–4 minutes at 180°C\n\nCore temperature check: all chicken must reach ≥75°C internal temperature. Use probe thermometer — sanitise probe between uses.\nIf below 75°C, return to fryer for 2 more minutes and re-check.` },
  { category: 'Food Preparation', title: 'Allergen Handling Procedure', content: `Crispy Coop allergen status:\n- GLUTEN: present in batter/breading (wheat flour)\n- MILK: present in buttermilk wash\n- EGGS: present in wash\n- SULPHITES: may be present in some sauces\n- CELERY: present in some seasoning blends\n- MUSTARD: present in some condiments\n- SESAME: bun sesame seeds (ask customers)\n\nFor allergen enquiries:\n1. STOP and give the customer your full attention\n2. Consult the Allergen Matrix (printed, laminated, on wall)\n3. Do NOT guess — if unsure, say "I need to check"\n4. Prepare allergen-free orders in clean area using dedicated utensils\n5. Package separately and label clearly\n6. Inform manager of all allergen orders` },
  { category: 'Food Preparation', title: 'Sauce Batch Preparation', content: `Sauces are prepared fresh in batches. Each batch must be:\n1. Labelled with: product name, date prepared, use-by date (3 days max)\n2. Stored in sealed container in fridge at ≤5°C\n3. Checked for colour/smell before use — discard if any doubt\n\nSignature Sauces:\n- Coop Sauce (mayo base): 3-day shelf life refrigerated\n- Hot Sauce: 5-day shelf life (vinegar preservative)\n- BBQ Glaze: 5-day shelf life\n- Garlic Aioli: 2-day shelf life (fresh garlic)\n\nNEVER top up existing batch — always prepare fresh\nNEVER leave sauces out of refrigeration for over 2 hours` },
  { category: 'Food Preparation', title: 'Coleslaw Preparation', content: `1. Wash hands thoroughly\n2. Shred white cabbage, carrot, and red onion using mandoline or food processor\n3. Dress with approved coleslaw dressing — ratio: 500g veg to 100ml dressing\n4. Mix thoroughly\n5. Label container with preparation date\n6. Use-by: 2 days refrigerated\n7. Do NOT prepare in advance more than 1 day\n8. NEVER serve coleslaw that has been left at room temperature over 1 hour` },
  { category: 'Food Preparation', title: 'Portion Control Standards', content: `Standard portion sizes — weigh using portion scales:\n\n- Chicken breast (bone-in): 180–200g raw\n- Chicken thigh (bone-in): 160–180g raw\n- Chicken tenders per serving: 4 pieces / 160g raw\n- Fries (regular): 130g cooked\n- Fries (large): 200g cooked\n- Coleslaw: 80g per serving\n- Sauces per pot: 30ml\n\nOver-portioning costs the business money. Under-portioning reduces customer satisfaction. Aim for the centre of the range. Weigh every 5th order to maintain accuracy.` },
  { category: 'Food Preparation', title: 'Hot Holding Temperature Standards', content: `All cooked food held for service must be maintained at ≥63°C.\n\nHolding cabinet rules:\n1. Pre-heat cabinet to 75°C before placing food\n2. Do NOT hold food for more than 30 minutes — quality degrades\n3. Check cabinet temperature every 30 minutes with probe thermometer\n4. Discard any food that has been held below 63°C for over 15 minutes\n5. Record holding temperatures in SFBB diary\n6. NEVER combine fresh food with held food\n7. Log all discards in CoopOS Wastage module with "Hot-held discard" reason` },
  { category: 'Food Preparation', title: 'Cross-Contamination Prevention', content: `Colour-coded board system:\n- RED board: raw meat only\n- BLUE board: raw fish (if applicable)\n- YELLOW board: cooked meat\n- GREEN board: salad and vegetables\n- WHITE board: bread and dairy\n- PURPLE board: allergen-free prep\n\nRules:\n1. NEVER use a board for a different purpose\n2. Sanitise boards between tasks even within the same colour\n3. Raw chicken and cooked food must never share storage space\n4. Separate tongs for raw and cooked — colour coded\n5. Wash hands between handling raw and cooked food\n6. Dedicated fridge for raw chicken (Fridge 1)` },

  // Hygiene & Sanitation (6)
  { category: 'Hygiene & Sanitation', title: 'Personal Hygiene Standards', content: `Required standards for all staff:\n1. Hair must be tied back and covered with a hat or hairnet\n2. No jewellery in kitchen (stud earrings only if necessary)\n3. Clean uniform every shift\n4. No nail varnish or false nails\n5. Wash hands:\n   - On arrival\n   - After touching face, hair, phone\n   - After using toilet\n   - After handling raw meat\n   - After handling waste\n   - After breaks\n6. Report any cuts — must be covered with blue waterproof plaster (provided)\n7. Do NOT work if suffering from sickness, diarrhoea, or food-borne illness — report to manager immediately and stay off for 48 hours after last symptom` },
  { category: 'Hygiene & Sanitation', title: 'Handwashing Procedure', content: `Correct handwashing technique (minimum 20 seconds):\n1. Wet hands with warm water\n2. Apply soap (provided at all sinks)\n3. Rub palms together\n4. Rub back of each hand\n5. Interlace fingers and rub between them\n6. Rub thumbs in rotating motion\n7. Rub fingertips on opposite palm\n8. Rinse thoroughly\n9. Dry with paper towel (NOT cloth towel)\n10. Use paper towel to turn off taps\n\nHand sanitiser is NOT a substitute for handwashing — it is a supplement.` },
  { category: 'Hygiene & Sanitation', title: 'Surface Sanitisation Routine', content: `Cleaning frequency:\n- EVERY 30 MINUTES: fryer area, prep stations during service\n- EVERY 2 HOURS: serving counter, packaging station\n- AFTER EVERY USE: chopping boards, utensils, scales\n- END OF SERVICE: full kitchen deep clean\n\nProcedure:\n1. Remove visible debris with paper towel — discard\n2. Apply approved food-safe sanitiser spray\n3. Leave for 30 seconds contact time (DO NOT wipe immediately)\n4. Wipe with clean cloth — use fresh cloth for each surface\n5. Allow to air dry\n\nCleaning chemical storage: keep separate from food — locked cupboard under prep station` },
  { category: 'Hygiene & Sanitation', title: 'Waste Management', content: `Bin types and locations:\n- Food waste: green bin, kitchen\n- Packaging waste: blue bin, kitchen\n- Oil waste: dedicated oil drum — collected by licensed contractor\n- Cardboard: flatten and stack in back yard — collected weekly\n\nRules:\n1. Empty bins when ¾ full — do not overfill\n2. Wear gloves when handling bin bags\n3. Tie bag tightly before removing from bin\n4. Replace liner immediately\n5. Clean bin with sanitiser after emptying\n6. Log all significant food waste in CoopOS Wastage module\n7. Pest risk: never leave bin lids open overnight` },
  { category: 'Hygiene & Sanitation', title: 'Pest Prevention Protocol', content: `1. Keep all delivery doors closed when not in use\n2. Seal all gaps around pipes and cables (report to manager)\n3. Store all food at least 15cm off the floor\n4. Never leave food or packaging outside overnight\n5. Check deliveries for signs of pest damage before accepting\n6. Report any sighting of mice, cockroaches, or flies to manager immediately\n7. Pest control contractor visits: quarterly minimum\n8. Log any sightings in SFBB Pest Control Log\n9. Keep drains clean — flush weekly with approved drain cleaner` },
  { category: 'Hygiene & Sanitation', title: 'Cleaning Chemical Safety', content: `All cleaning chemicals on site:\n1. Food-safe surface sanitiser (green label) — for food contact surfaces\n2. Degreaser (yellow label) — for equipment and extraction\n3. Drain unblocker (red label) — CORROSIVE, gloves and eye protection mandatory\n4. Floor cleaner (blue label) — anti-slip\n\nRules:\n- NEVER mix chemicals\n- Always read label before use\n- Store in locked cupboard away from food\n- Use correct PPE: gloves for all, eye protection for drain unblocker\n- COSHH data sheets are in the red binder by the back door\n- Report any spills immediately — use spill kit (located next to COSHH folder)` },

  // Customer Service (5)
  { category: 'Customer Service', title: 'Customer Greeting Standards', content: `Every customer must be greeted within 10 seconds of entering.\n\nStandard greeting:\n"Hi, welcome to Crispy Coop! What can I get you today?"\n\nService standards:\n1. Make eye contact and smile\n2. Be attentive but not pushy\n3. Know the menu — be able to describe every item\n4. Upsell naturally: "Would you like to make that a meal?"\n5. Repeat the order back to the customer before charging\n6. Give an accurate wait time if longer than 5 minutes\n7. Thank every customer as they leave\n\nPhone manner:\n"Good [morning/afternoon/evening], Crispy Coop Hertford, how can I help?"` },
  { category: 'Customer Service', title: 'Complaint Handling Procedure', content: `Step 1: Listen — don't interrupt, let the customer fully explain.\nStep 2: Apologise — "I'm really sorry to hear that."\nStep 3: Investigate — check the order, check if the product matches.\nStep 4: Resolve — offer one of:\n  - Replacement dish (preferred if food quality issue)\n  - Partial refund if appropriate\n  - Full refund for serious complaint\n\nDo NOT:\n- Argue with the customer\n- Offer discounts you're not authorised to give\n- Ask the customer to call back later\n\nEscalate to manager for:\n- Any complaint involving allergens\n- Any complaint involving illness\n- Any complaint involving a refund over £20\n\nLog all complaints in CoopOS Customers → Complaints module same day.` },
  { category: 'Customer Service', title: 'Food Allergy Enquiry Protocol', content: `When a customer mentions an allergy:\n1. STOP all other tasks — this takes priority\n2. Ask: "Which allergen are you concerned about?"\n3. Refer to the allergen matrix on the wall\n4. If you are unsure of ANY ingredient, do not guess — say "Let me check with the kitchen"\n5. Do NOT rely on memory\n6. Prepare the order in a clean area with dedicated utensils if allergen-free\n7. Package separately — add "ALLERGEN ORDER" label\n8. Personally deliver to counter — do not mix with other orders\n9. If you cannot safely accommodate, say so honestly\n\nNEVER say something is safe if you're not 100% certain. Customer health > customer satisfaction.` },
  { category: 'Customer Service', title: 'Online Order Management', content: `Delivery platform order processing:\n1. Accept order within 60 seconds of it appearing — failure to accept results in cancellation penalties\n2. Set correct prep time — aim for accuracy\n3. Prepare delivery orders with the same quality standard as walk-in\n4. Package securely: tape bags for delivery orders\n5. Add correct condiments and napkins\n6. Mark order as ready when it leaves the kitchen\n7. Never cancel an order without manager approval\n\nFor issues:\n- Late driver: mark as ready on platform to stop customer timer\n- Missing item complaint: log in CoopOS Delivery → Disputes\n- Wrong order: take photo evidence before replacing` },
  { category: 'Customer Service', title: 'Queue Management During Rush', content: `During peak trading hours (12–2 PM, 5–8 PM):\n1. Call estimated wait times clearly: "That'll be about 10 minutes"\n2. Take orders in advance of immediate capacity\n3. Keep order tracking visible — don't lose tickets\n4. Communicate any delays proactively — don't let customers chase\n5. Station assignments during rush:\n   - 1 person: till and order taking\n   - 1 person: frying\n   - 1 person: boxing and service\n6. If queue exceeds 10 customers, alert manager to open extra station\n7. Never rush food quality to reduce wait time — inform customer instead` },

  // Cash Handling (4)
  { category: 'Cash Handling', title: 'Cash Handling Policy', content: `Authorised cash handlers: Manager and Owner only (except till float)\n\nRules:\n1. Count float at opening and record\n2. No cash to remain on counter — all cash into till immediately\n3. Call out denomination when receiving notes: "Tenner received"\n4. Check suspect notes with UV pen (kept at till)\n5. Never open safe with a customer present\n6. Minimum till float: £150 (standard), £200 (weekend)\n7. If till exceeds £500 cash, call manager for mid-session drop\n8. Safe code: provided by owner during onboarding — do NOT share\n9. Report any discrepancies immediately — do not attempt to correct without manager\n10. Record all till counts in CoopOS Finance → Cash Log` },
  { category: 'Cash Handling', title: 'Counterfeit Note Detection', content: `Checks for suspect notes:\n1. UV pen: mark the note — genuine notes show no change, counterfeits turn dark\n2. Watermark: hold up to light — should see face of monarch\n3. Security thread: vertical metallic strip — should be embedded in note\n4. Raised print: feel the numbers on the note — should be tactile\n5. Colour-shift ink: on £50 and some £20 notes\n\nIf you suspect a counterfeit:\n1. Do NOT return it to the customer\n2. Call manager immediately\n3. Do NOT accuse the customer\n4. Note customer description if possible\n5. Report to police if confirmed — Hertfordshire Police non-emergency: 101` },
  { category: 'Cash Handling', title: 'Till Discrepancy Procedure', content: `A discrepancy is any difference between POS Z-report total and physical cash count.\n\nSmall discrepancy (under £5):\n- Record on cash sheet with note\n- Report to manager but no escalation needed\n\nMedium discrepancy (£5–£20):\n- Manager must be present for investigation\n- Review last 10 transactions on POS\n- Check if any void transactions\n\nLarge discrepancy (over £20):\n- Manager locks till and secures cash\n- Full shift review required\n- CCTV may be reviewed if theft suspected\n- Owner must be informed same day` },
  { category: 'Cash Handling', title: 'Refund and Void Procedure', content: `Refunds:\n1. Only manager can authorise refunds over £10\n2. Check product — was there a genuine fault?\n3. Process refund on POS — select original transaction\n4. Cash refunds: from till with manager present\n5. Card refunds: process via card machine — can take 3–5 working days\n6. Record all refunds in CoopOS Finance module with reason\n\nVoid transactions:\n1. Void only if order has NOT been prepared\n2. Once food is prepared, it is a refund not a void\n3. All voids must have manager approval and reason entered in POS` },

  // Equipment Operation (5)
  { category: 'Equipment Operation', title: 'Fryer Operation and Safety', content: `Pre-operation:\n1. Confirm oil is fresh and at correct level\n2. Confirm temperature has reached 175°C before use\n3. Keep area clear of water — water in hot oil causes violent splatter (BURN RISK)\n\nDuring operation:\n1. Lower baskets slowly — never drop\n2. Do not overload baskets — maximum ¾ full\n3. Stay at fryer when in use\n4. Keep fire blanket accessible at all times\n5. If oil catches fire: do NOT use water — smother with fire blanket or CO2 extinguisher\n\nPost-operation:\n1. Turn off after service\n2. Allow to cool before cleaning\n3. Filter or change oil per schedule\n4. Log any issues in CoopOS Equipment module` },
  { category: 'Equipment Operation', title: 'Grill Operation Procedure', content: `1. Pre-heat grill to 220°C minimum before use\n2. Clean grill plates with grill stone before starting — remove previous residue\n3. Lightly oil grill surface before first items\n4. Place items perpendicular to grill lines for crosshatch marks\n5. Do NOT press down on chicken — traps juices, reduces quality\n6. Turn once — halfway through cooking time\n7. Check internal temperature with probe: ≥75°C before service\n8. Clean grill plates between batches — use damp cloth (CAUTION: steam)\n9. Full clean at end of service per closing SOP` },
  { category: 'Equipment Operation', title: 'Holding Cabinet Operation', content: `1. Pre-heat to 75°C at least 30 minutes before service\n2. Only place COOKED food in holding cabinet\n3. Do NOT place raw or partially cooked items in cabinet\n4. Maximum hold time: 30 minutes per Crispy Coop quality standard\n5. Check temperature with probe every 30 minutes — must be ≥63°C\n6. Label all items with time placed in cabinet\n7. Discard any item held over 30 minutes — log in CoopOS Wastage\n8. Never stack containers — heat circulation is restricted\n9. Report any temperature failures to manager immediately` },
  { category: 'Equipment Operation', title: 'Refrigeration Unit Checks', content: `Daily checks:\n- Check thermometer display on each unit at opening and closing\n- If display is not working, use calibrated probe thermometer\n- Target temperatures:\n  - Raw chicken fridge: ≤3°C\n  - Cooked/prepared fridge: ≤5°C\n  - Freezer: ≤-18°C\n\nWhat to check:\n1. Door seals — no tears or gaps\n2. Door closes fully and latches\n3. No ice build-up inside (indicates door seal failure)\n4. Condenser coils at rear — keep clear of debris\n\nIf temperature is out of range:\n1. Do not use the unit\n2. Identify safe temporary storage\n3. Contact equipment contractor (details in CoopOS Equipment module)\n4. Log issue in CoopOS Equipment → Repairs` },
  { category: 'Equipment Operation', title: 'POS Terminal Troubleshooting', content: `Common issues and fixes:\n\nScreen frozen: hold power button 10 seconds, restart\nPrinter not printing: check paper roll (replace if needed), check cable connection\nCard machine not connecting: restart card machine, check Wi-Fi\nPlatform tablet not loading: restart, check Wi-Fi password hasn't changed\nLoss of network: check router, call BT Openreach if persistent (number in back office)\n\nDo NOT attempt to open or dismantle any equipment.\nFor all hardware faults not resolved above, contact manager.\nFor software faults, contact POS supplier: details in CoopOS Equipment module.` },

  // Health & Safety (5)
  { category: 'Health & Safety', title: 'Fire Safety Procedure', content: `In the event of fire:\n1. Shout "FIRE" to alert all staff\n2. Call 999 immediately\n3. Do NOT attempt to fight a large fire — evacuate\n4. For small fryer fire: turn off fryer, use fire blanket\n5. Evacuate all customers and staff through nearest exit\n6. Meet at assembly point: car park across the road\n7. Do NOT re-enter the building until fire service gives all-clear\n8. Account for all staff at assembly point\n\nFire extinguisher types on site:\n- CO2 (black): electrical fires, fryer fires\n- Foam (cream): general fires\n- Fire blanket: fryer/chip pan fires\n\nFire alarm test: every Tuesday 9:30 AM (arranged by owner)` },
  { category: 'Health & Safety', title: 'Accident and Incident Reporting', content: `For any accident involving injury:\n1. Assess the situation — call 999 if serious\n2. First aid kit: located under prep counter (main kitchen)\n3. Provide first aid — trained first aider: see rota for current first-aider\n4. Record incident in Accident Book (red folder, back office)\n5. Log in CoopOS via manager\n6. Notify owner same day for any RIDDOR-reportable incident\n\nRIDDOR reportable events (must report to HSE within 10 days):\n- Fractures (not fingers or toes)\n- Amputations\n- Unconsciousness\n- Any injury requiring hospital admission\n\nNear misses must also be logged — they prevent future accidents.` },
  { category: 'Health & Safety', title: 'Manual Handling — Safe Lifting', content: `Crispy Coop receives regular deliveries of heavy stock (oil, flour, chicken boxes).\n\nSafe lifting technique:\n1. Assess the load — do NOT lift if it feels too heavy — ask for help\n2. Stand close to the load\n3. Feet shoulder-width apart\n4. Bend knees — keep back straight (neutral spine)\n5. Get a firm grip\n6. Lift by straightening legs — NOT your back\n7. Hold load close to body\n8. Turn by moving feet — do NOT twist your back while holding load\n\nMaximum single-person lift: 25kg (standard oil drum: ~20kg)\nFor heavier loads: use sack truck (kept in back room) or ask for help` },
  { category: 'Health & Safety', title: 'Slip and Trip Prevention', content: `Most common kitchen injuries are slips on wet floors.\n\nPrevention:\n1. Mop up spills immediately — place wet floor sign\n2. Anti-slip mats must be in place at all stations\n3. Anti-slip footwear is mandatory for all kitchen staff\n4. Keep walkways clear — no boxes or equipment in aisles\n5. Cable management: no loose cables across walkways\n6. Adequate lighting — report any failed bulbs immediately\n7. Report any damaged flooring to manager\n\nWet floor signs: stored at back of kitchen — use whenever mopping.` },
  { category: 'Health & Safety', title: 'First Aid and Emergency Contacts', content: `First aid kit location: under prep counter, main kitchen\n\nEmergency contacts:\n- Emergency services: 999\n- HSE incident line: 0345 300 9923\n- Hertfordshire Police (non-emergency): 101\n- Environmental Health (food safety emergency): 01992 555555\n\nFirst aider on rota: check weekly schedule\n\nFirst aid kit contents check: first Monday of each month\nLog any items used and restock from supply cabinet.\n\nFirst aid kit contents:\n- Assorted plasters (blue for kitchen)\n- Sterile dressings\n- Eye wash\n- Burn gel and dressings\n- Disposable gloves\n- Foil blanket\n- CPR face shield` },

  // Delivery Operations (5)
  { category: 'Delivery Operations', title: 'Delivery Order Packaging Standards', content: `All delivery orders must be packaged to prevent:\n- Temperature loss\n- Spillage\n- Contamination\n\nPackaging requirements:\n1. Hot items in insulated boxes — use foil lining for long-distance orders\n2. Sauces in sealed pots — double bag if multiple\n3. Drinks upright in cup holders — separate bag from food\n4. Seal every bag with tape — label tape with order number\n5. Allergen orders: bright red "ALLERGEN" sticker on bag\n6. Check contents against order receipt before sealing\n7. Never stack heavy items on top of boxes\n\nQuality standard: food must arrive as if served in-store.` },
  { category: 'Delivery Operations', title: 'Delivery Dispute Procedure', content: `When a customer reports an issue via delivery platform:\n1. Check the platform notification immediately\n2. Do NOT dismiss without reading\n3. Assess the claim:\n   - Missing item: check if it was packed (check CCTV if available)\n   - Wrong order: check kitchen tickets\n   - Quality complaint: note details\n4. Respond within the platform's response window (typically 24–48 hours)\n5. Log all disputes in CoopOS Delivery → Disputes module on same day\n6. Evidence: take photos of every delivery bag before it leaves if disputed orders are common\n7. Dispute over £20: escalate to manager for formal response` },
  { category: 'Delivery Operations', title: 'Driver Handover Protocol', content: `When handing over an order to a delivery driver:\n1. Check driver's name against order on platform\n2. Confirm order number verbally\n3. Hand over bag securely — do NOT leave on counter unattended\n4. If driver refuses to take order: mark as handed over on platform anyway, note on order\n5. If order sits for over 20 minutes: contact platform to reassign driver\n6. For Uber Eats: swipe "Handed to driver" on tablet\n7. For Just Eat: mark as dispatched on tablet\n8. For Deliveroo: confirm handover in app\n9. Log any incidents in CoopOS Delivery module` },
  { category: 'Delivery Operations', title: 'Platform Downtime Procedure', content: `If a delivery platform goes offline during service:\n1. Check platform app for outage notice\n2. Check platform status page (URLs bookmarked on tablets)\n3. If confirmed outage: note start time, resume when restored\n4. Log the downtime event in CoopOS Finance → Platform Payouts (for record)\n5. If downtime is longer than 2 hours: contact platform support\n6. If only one platform is down: maintain service on others\n7. Do NOT manually take delivery orders by phone unless manager authorises\n8. Review lost order volume after event — log for business intelligence` },
  { category: 'Delivery Operations', title: 'Delivery Rating Management', content: `Delivery ratings directly affect platform search ranking and sales.\n\nTo maintain high ratings:\n1. Accuracy: double-check every order against receipt\n2. Presentation: food must look good in the box\n3. Speed: aim to be ready within advertised prep time\n4. Temperature: hot food must be hot at delivery\n\nWhen a negative rating is received:\n1. Read the feedback carefully\n2. If actionable: brief team and correct\n3. If unfair: use platform response system (manager only)\n4. Log rating events in CoopOS Delivery → Rating History\n5. Target ratings: Uber Eats ≥4.5, Just Eat ≥90%, Deliveroo ≥4.5` },

  // Staff Management (5)
  { category: 'Staff Management', title: 'Shift Handover Procedure', content: `When handing over a shift:\n1. Brief incoming team on:\n   - Current stock levels and any shortages\n   - Any outstanding orders or deliveries expected\n   - Any equipment issues\n   - Any customer complaints or incidents from your shift\n2. Hand over any open disputes or escalations\n3. Complete your section of the CoopOS shift log\n4. Count and confirm till float with incoming manager\n5. Ensure kitchen is clean and stocked to incoming standards\n6. Do NOT leave until incoming team are ready to take over\n7. Be professional — leave the shift better than you found it` },
  { category: 'Staff Management', title: 'New Staff Induction Checklist', content: `Before first solo shift, new staff must complete:\n[ ] Read and sign this SOP library (CoopOS SOP module)\n[ ] Complete food hygiene awareness training\n[ ] Watch: fryer safety video (YouTube link pinned in WhatsApp)\n[ ] Shadow experienced staff for minimum 2 shifts\n[ ] Demonstrate safe: handwashing, temperature checks, allergen response\n[ ] Receive and memorise: alarm code, safe code (manager discretion), Wi-Fi password\n[ ] Set up CoopOS PIN login\n[ ] Complete emergency contact form\n[ ] Confirm bank details and right-to-work documents provided\n\nManager signs off on CoopOS Training module when complete.` },
  { category: 'Staff Management', title: 'Absence Reporting Procedure', content: `If you are unable to attend your shift:\n1. Notify manager as early as possible — minimum 2 hours before shift\n2. Call the manager directly — do NOT just send a text message\n3. State reason and estimated duration of absence\n4. If illness, confirm when you expect to return\n5. Food handler rules: no return to work until 48 hours symptom-free (sickness/diarrhoea)\n6. Manager logs absence in CoopOS Staff → Absences\n7. Persistent short-notice absences will be reviewed in 1-to-1\n\nCovering your shift:\n- You are responsible for finding cover — check WhatsApp group\n- Manager has final approval on all cover arrangements` },
  { category: 'Staff Management', title: 'Disciplinary Procedure Overview', content: `This SOP provides an overview — full policy is held by the owner.\n\nStages:\n1. Informal verbal warning — for minor first-time issues\n2. Formal verbal warning — documented in writing\n3. Written warning — formal HR record\n4. Final written warning or dismissal\n\nGrounds for immediate dismissal (gross misconduct):\n- Theft from the business\n- Fighting on premises\n- Being under the influence of alcohol or drugs\n- Discrimination or harassment\n- Serious breach of food safety (deliberate or negligent)\n\nAll disciplinary actions must be logged. Staff have the right to be accompanied at any formal disciplinary meeting.` },
  { category: 'Staff Management', title: 'Uniform and Appearance Standards', content: `Required uniform (provided by Crispy Coop):\n- Branded polo shirt or t-shirt\n- Black trousers or dark-coloured chinos\n- Apron when in kitchen\n- Non-slip safety footwear (your own — must meet standard)\n- Hair cover when in kitchen (hat or hairnet provided)\n\nPersonal appearance:\n- No strong perfumes or aftershave in kitchen\n- No nail varnish or false nails in kitchen\n- Piercings: stud earrings only — no nose rings, eyebrow bars, or gauges\n- Beard nets required for beards when working in kitchen (provided)\n\nUniform must be clean at the start of every shift. Stained or damaged uniforms must be reported to manager for replacement.` },
] as const
